//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Game Lad.rc
//
#define IDS_FILE_OPEN                   1
#define IDS_FILE_CLOSE                  2
#define IDS_FILE_SAVESTATE              3
#define ID_ADDCODE                      3
#define IDS_FILE_LOADSTATE              4
#define ID_ADDCHEAT                     4
#define IDS_FILE_SAVESTATEAS            5
#define IDS_FILE_LOADSTATEAS            6
#define IDS_FILE_STATESLOT_0            7
#define IDS_FILE_STATESLOT_1            8
#define IDS_FILE_STATESLOT_2            9
#define IDS_FILE_STATESLOT_3            10
#define IDS_FILE_STATESLOT_4            11
#define IDS_FILE_STATESLOT_5            12
#define IDS_FILE_STATESLOT_6            13
#define IDS_FILE_STATESLOT_7            14
#define IDS_FILE_STATESLOT_8            15
#define IDS_FILE_STATESLOT_9            16
#define IDS_FILE_SAVEBATTERY            17
#define IDS_FILE_LOADBATTERY            18
#define IDS_FILE_SAVEBATTERYAS          19
#define IDS_FILE_CLEARBATTERY           20
#define IDS_FILE_EXIT                   21
#define IDS_EDIT_GOTO                   22
#define IDS_VIEW_DISASSEMBLY            23
#define IDS_VIEW_MEMORY                 24
#define IDS_VIEW_REGISTERS              25
#define IDS_VIEW_HARDWARE               26
#define IDS_VIEW_PALETTES               27
#define IDS_VIEW_TILEMAP                28
#define IDS_VIEW_TILES                  29
#define IDS_VIEW_STATUSBAR              30
#define IDS_VIEW_ZOOM_100               31
#define IDS_VIEW_ZOOM_200               32
#define IDS_VIEW_ZOOM_300               33
#define IDS_VIEW_ZOOM_400               34
#define IDS_VIEW_FRAMESKIP_0            35
#define IDS_VIEW_FRAMESKIP_1            36
#define IDS_VIEW_FRAMESKIP_2            37
#define IDS_VIEW_FRAMESKIP_3            38
#define IDS_VIEW_FRAMESKIP_4            39
#define IDS_VIEW_FRAMESKIP_5            40
#define IDS_VIEW_FRAMESKIP_6            41
#define IDS_VIEW_FRAMESKIP_7            42
#define IDS_VIEW_FRAMESKIP_8            43
#define IDS_VIEW_FRAMESKIP_9            44
#define IDS_MEMORY_ROM                  45
#define IDS_MEMORY_VBK_BANK0            46
#define IDS_MEMORY_VBK_BANK1            47
#define IDS_MEMORY_RAM_BANK0            48
#define IDS_MEMORY_RAM_BANK1            49
#define IDS_MEMORY_RAM_BANK2            50
#define IDS_MEMORY_RAM_BANK3            51
#define IDS_MEMORY_RAM_BANK4            52
#define IDS_MEMORY_RAM_BANK5            53
#define IDS_MEMORY_RAM_BANK6            54
#define IDS_MEMORY_RAM_BANK7            55
#define IDS_MEMORY_RAM_BANK8            56
#define IDS_MEMORY_RAM_BANK9            57
#define IDS_MEMORY_RAM_BANK10           58
#define IDS_MEMORY_RAM_BANK11           59
#define IDS_MEMORY_RAM_BANK12           60
#define IDS_MEMORY_RAM_BANK13           61
#define IDS_MEMORY_RAM_BANK14           62
#define IDS_MEMORY_RAM_BANK15           63
#define IDS_MEMORY_SVBK_BANK1           64
#define IDS_MEMORY_SVBK_BANK2           65
#define IDS_MEMORY_SVBK_BANK3           66
#define IDS_MEMORY_SVBK_BANK4           67
#define IDS_MEMORY_SVBK_BANK5           68
#define IDS_MEMORY_SVBK_BANK6           69
#define IDS_MEMORY_SVBK_BANK7           70
#define IDS_EMULATION_STARTDEBUG        71
#define IDS_EMULATION_EXECUTE           72
#define IDS_EMULATION_STOP              73
#define IDS_EMULATION_STEPINTO          74
#define IDS_EMULATION_STEPOVER          75
#define IDS_EMULATION_STEPOUT           76
#define IDS_EMULATION_RUNTOCURSOR       77
#define IDS_EMULATION_SETNEXTSTATEMENT  78
#define IDS_EMULATION_TOGGLEBREAKPOINT  79
#define IDS_EMULATION_RESET             80
#define IDS_TOOLS_OPTIONS               81
#define IDS_TOOLS_SOUNDENABLED          82
#define IDS_WINDOW_NEXT                 83
#define IDS_WINDOW_PREVIOUS             84
#define IDS_WINDOW_CASCADE              85
#define IDS_WINDOW_TILEHORIZONTALLY     86
#define IDS_WINDOW_TILEVERTICALLY       87
#define IDS_HELP_ABOUT                  88
#define IDS_ABOUT_TITLE                 89
#define IDS_ABOUT_WRITTENBY             90
#define IDS_TRANSLATOR_NAME             91
#define IDS_FILE_MENU                   92
#define IDS_FILE_OPEN_MENU              93
#define IDS_FILE_CLOSE_MENU             94
#define IDS_FILE_SAVESTATE_MENU         95
#define IDS_FILE_LOADSTATE_MENU         96
#define IDS_FILE_SAVESTATEAS_MENU       97
#define IDS_FILE_LOADSTATEAS_MENU       98
#define IDS_FILE_STATESLOT_MENU         99
#define IDS_FILE_STATESLOT_0_MENU       100
#define IDS_FILE_STATESLOT_1_MENU       101
#define IDS_FILE_STATESLOT_2_MENU       102
#define IDS_FILE_STATESLOT_3_MENU       103
#define IDS_FILE_STATESLOT_4_MENU       104
#define IDS_FILE_STATESLOT_5_MENU       105
#define IDI_MAINICON                    106
#define IDS_FILE_STATESLOT_6_MENU       106
#define IDD_ABOUT                       107
#define IDS_FILE_STATESLOT_7_MENU       107
#define IDD_OPTIONS_KEYS                108
#define IDS_FILE_STATESLOT_8_MENU       108
#define IDS_FILE_STATESLOT_9_MENU       109
#define IDS_FILE_SAVEBATTERY_MENU       110
#define IDS_FILE_LOADBATTERY_MENU       111
#define IDS_FILE_SAVEBATTERYAS_MENU     112
#define IDS_FILE_CLEARBATTERY_MENU      113
#define IDS_FILE_EXIT_MENU              114
#define ID_MEMORY_RAM_BANK0             115
#define IDS_EDIT_MENU                   115
#define IDR_ACCELERATOR                 116
#define ID_MEMORY_RAM_BANK1             116
#define IDS_EDIT_GOTO_MENU              116
#define ID_MEMORY_RAM_BANK2             117
#define IDS_VIEW_MENU                   117
#define IDB_CURRENTSTATEMENT            118
#define ID_MEMORY_RAM_BANK3             118
#define IDS_VIEW_DISASSEMBLY_MENU       118
#define IDB_BREAKPOINT                  119
#define ID_MEMORY_RAM_BANK4             119
#define IDS_VIEW_MEMORY_MENU            119
#define IDI_ICON1                       120
#define ID_MEMORY_RAM_BANK5             120
#define IDS_VIEW_REGISTERS_MENU         120
#define IDI_ICON2                       121
#define ID_MEMORY_RAM_BANK6             121
#define IDS_VIEW_HARDWARE_MENU          121
#define IDI_ICON3                       122
#define ID_MEMORY_RAM_BANK7             122
#define IDS_VIEW_PALETTES_MENU          122
#define IDI_ICON4                       123
#define ID_MEMORY_RAM_BANK8             123
#define IDS_VIEW_TILEMAP_MENU           123
#define IDI_ICON5                       124
#define ID_MEMORY_RAM_BANK9             124
#define IDS_VIEW_TILES_MENU             124
#define IDI_ICON6                       125
#define ID_MEMORY_RAM_BANK10            125
#define IDS_VIEW_STATUSBAR_MENU         125
#define ID_MEMORY_RAM_BANK11            126
#define IDS_VIEW_ZOOM_MENU              126
#define ID_MEMORY_RAM_BANK12            127
#define IDD_ENTERNUMBER                 127
#define IDS_VIEW_ZOOM_100_MENU          127
#define ID_MEMORY_RAM_BANK13            128
#define IDS_VIEW_ZOOM_200_MENU          128
#define IDD_OPTIONS_FILE                128
#define ID_MEMORY_RAM_BANK14            129
#define IDS_VIEW_ZOOM_300_MENU          129
#define IDD_OPTIONS_GENERAL             129
#define ID_MEMORY_RAM_BANK15            130
#define IDS_VIEW_ZOOM_400_MENU          130
#define ID_TILEMAP_PALETTENO            131
#define IDS_VIEW_FRAMESKIP_MENU         131
#define IDD_CHEAT                       131
#define ID_TILEMAP_FLIPX                132
#define IDS_VIEW_FRAMESKIP_0_MENU       132
#define ID_TILEMAP_FLIPY                133
#define IDS_VIEW_FRAMESKIP_1_MENU       133
#define ID_TILEMAP_PRIORITY             134
#define IDS_VIEW_FRAMESKIP_2_MENU       134
#define IDS_VIEW_FRAMESKIP_3_MENU       135
#define ID_TILEMAP_TILENO               136
#define IDS_VIEW_FRAMESKIP_4_MENU       136
#define ID_TILEMAP_TILEDATA             137
#define IDS_VIEW_FRAMESKIP_5_MENU       137
#define ID_TILEMAP_BGADDRESS            138
#define IDS_VIEW_FRAMESKIP_6_MENU       138
#define ID_TILEMAP_WNDADDRESS           139
#define IDS_VIEW_FRAMESKIP_7_MENU       139
#define ID_TILEMAP_BGENABLED            140
#define IDS_VIEW_FRAMESKIP_8_MENU       140
#define ID_TILEMAP_WNDENABLED           141
#define IDS_VIEW_FRAMESKIP_9_MENU       141
#define ID_TILES_PALETTENO              142
#define IDS_VIEW_BANK_MENU              142
#define IDS_VIEW_BANK_ROM_MENU          143
#define ID_TOOLS_CHEAT                  143
#define IDS_VIEW_BANK_VBK_MENU          144
#define ID_FILE_SAVEVIDEOAS             144
#define IDS_VIEW_BANK_VBK_0_MENU        145
#define ID_FILE_SAVESNAPSHOTAS          145
#define IDS_VIEW_BANK_VBK_1_MENU        146
#define ID_FILE_MERGECHEATS             146
#define IDS_VIEW_BANK_RAM_MENU          147
#define ID_TOOLS_LINKCABLE              147
#define IDS_VIEW_BANK_RAM_0_MENU        148
#define ID_DEBUG_COMMAND1               148
#define IDS_VIEW_BANK_RAM_1_MENU        149
#define ID_TOOLS_SEARCHCHEAT            149
#define IDS_VIEW_BANK_RAM_2_MENU        150
#define ID_SEARCHCHEAT_NEWSEARCH        150
#define IDS_VIEW_BANK_RAM_3_MENU        151
#define ID_SEARCHCHEAT_EQUAL            151
#define IDS_VIEW_BANK_RAM_4_MENU        152
#define ID_SEARCHCHEAT_LESSEQUAL        152
#define IDS_VIEW_BANK_RAM_5_MENU        153
#define ID_SEARCHCHEAT_MOREEQUAL        153
#define IDS_VIEW_BANK_RAM_6_MENU        154
#define IDC_LIST                        154
#define IDS_VIEW_BANK_RAM_7_MENU        155
#define ID_SEARCHCHEAT_LESS             155
#define IDS_VIEW_BANK_RAM_8_MENU        156
#define ID_SEARCHCHEAT_MORE             156
#define IDS_VIEW_BANK_RAM_9_MENU        157
#define ID_SEARCHCHEAT_NOTEQUAL         157
#define IDS_VIEW_BANK_RAM_10_MENU       158
#define ID_SEARCHCHEAT_RELATIVELAST     158
#define IDS_VIEW_BANK_RAM_11_MENU       159
#define ID_SEARCHCHEAT_RELATIVEVALUE    159
#define IDS_VIEW_BANK_RAM_12_MENU       160
#define ID_SEARCHCHEAT_NAME             160
#define IDS_VIEW_BANK_RAM_13_MENU       161
#define ID_SEARCHCHEAT_HEX              161
#define IDS_VIEW_BANK_RAM_14_MENU       162
#define ID_SEARCHCHEAT_DEC              162
#define IDS_VIEW_BANK_RAM_15_MENU       163
#define IDS_VIEW_BANK_SVBK_MENU         164
#define IDS_VIEW_BANK_SVBK_1_MENU       165
#define IDS_VIEW_BANK_SVBK_2_MENU       166
#define IDS_VIEW_BANK_SVBK_3_MENU       167
#define IDS_VIEW_BANK_SVBK_4_MENU       168
#define IDS_VIEW_BANK_SVBK_5_MENU       169
#define IDS_VIEW_BANK_SVBK_6_MENU       170
#define IDS_VIEW_BANK_SVBK_7_MENU       171
#define IDS_EMULATION_MENU              172
#define IDS_EMULATION_STARTDEBUG_MENU   173
#define IDS_EMULATION_EXECUTE_MENU      174
#define IDS_EMULATION_STOP_MENU         175
#define IDS_EMULATION_STEPINTO_MENU     176
#define IDS_EMULATION_STEPOVER_MENU     177
#define IDS_EMULATION_STEPOUT_MENU      178
#define IDS_EMULATION_RUNTOCURSOR_MENU  179
#define IDS_EMULATION_SETNEXTSTATEMENT_MENU 180
#define IDS_EMULATION_TOGGLEBREAKPOINT_MENU 181
#define IDS_EMULATION_RESET_MENU        182
#define IDS_TOOLS_MENU                  183
#define IDS_TOOLS_OPTIONS_MENU          184
#define IDS_TOOLS_SOUNDENABLED_MENU     185
#define IDS_WINDOW_MENU                 186
#define IDS_WINDOW_NEXT_MENU            187
#define IDS_WINDOW_PREVIOUS_MENU        188
#define IDS_WINDOW_CASCADE_MENU         189
#define IDS_WINDOW_TILEHORIZONTALLY_MENU 190
#define IDS_WINDOW_TILEVERTICALLY_MENU  191
#define IDS_HELP_MENU                   192
#define IDS_HELP_ABOUT_MENU             193
#define IDS_STATUS_READY                194
#define IDS_STATUS_ENTERSLOTNUMBER      195
#define IDS_OPEN_TITLE                  196
#define IDS_OPEN_LOADBATTERY            197
#define IDS_STOPPED                     198
#define IDS_STARTDEBUG                  199
#define IDS_EXECUTE                     200
#define IDS_VK_APPS                     201
#define IDS_VK_BACK                     202
#define IDS_VK_CONTROL                  203
#define IDS_VK_DELETE                   204
#define IDS_VK_DOWN                     205
#define IDS_VK_END                      206
#define IDS_VK_RETURN                   207
#define IDS_VK_HOME                     208
#define IDS_VK_INSERT                   209
#define IDS_VK_LEFT                     210
#define IDS_VK_NUMLOCK                  211
#define IDS_VK_NUMPAD0                  212
#define IDS_VK_NUMPAD1                  213
#define IDS_VK_NUMPAD2                  214
#define IDS_VK_NUMPAD3                  215
#define IDS_VK_NUMPAD4                  216
#define IDS_VK_NUMPAD5                  217
#define IDS_VK_NUMPAD6                  218
#define IDS_VK_NUMPAD7                  219
#define IDS_VK_NUMPAD8                  220
#define IDS_VK_NUMPAD9                  221
#define IDS_VK_ADD                      222
#define IDS_VK_DECIMAL                  223
#define IDS_VK_DIVIDE                   224
#define IDS_VK_MULTIPLY                 225
#define IDS_VK_SUBTRACT                 226
#define IDS_VK_NEXT                     227
#define IDS_VK_PRIOR                    228
#define IDS_VK_PAUSE                    229
#define IDS_VK_RIGHT                    230
#define IDS_VK_SHIFT                    231
#define IDS_VK_SPACE                    232
#define IDS_VK_TAB                      233
#define IDS_VK_UP                       234
#define IDS_YES                         235
#define IDS_NO                          236
#define IDS_PROMPT                      237
#define IDS_OPTIONS_KEYS                238
#define IDS_OPTIONS_KEYS_UP             239
#define IDS_OPTIONS_KEYS_DOWN           240
#define IDS_OPTIONS_KEYS_LEFT           241
#define IDS_OPTIONS_KEYS_RIGHT          242
#define IDS_OPTIONS_KEYS_A              243
#define IDS_OPTIONS_KEYS_B              244
#define IDS_OPTIONS_KEYS_START          245
#define IDS_OPTIONS_KEYS_SELECT         246
#define IDS_OPTIONS_KEYS_FASTFORWARD    247
#define IDS_OPTIONS_GENERAL             248
#define IDS_FILEASSOC_FRAME             249
#define IDS_FILEASSOC_GB                250
#define IDS_FILEASSOC_GLS               251
#define IDS_SAVE_FRAME                  252
#define IDS_SAVE_LOADBATTERY            253
#define IDS_SAVE_LOADSTATE              254
#define IDS_SAVE_SAVEBATTERY            255
#define IDS_SAVE_SAVESTATE              256
#define IDS_MISC_FRAME                  257
#define IDS_MISC_FRAMESKIP              258
#define IDS_MISC_HARDWARE               259
#define IDS_MISC_AUTOSTART              260
#define IDS_OPTIONS_LANGUAGE            261
#define IDS_OPTIONS                     262
#define IDS_OPEN_GBROM                  263
#define IDS_OPEN_ALLFILES               264
#define IDS_OPEN_BATTERY                265
#define IDS_OPEN_SAVESTATE              266
#define IDS_WND_REGISTERS               267
#define IDS_WND_DISASSEMBLY             268
#define IDS_WND_MEMORY                  269
#define IDS_WND_TILES                   270
#define IDS_WND_TILEMAP                 271
#define IDS_WND_PALETTES                272
#define IDS_WND_HARDWARE                273
#define IDS_OPEN                        274
#define IDS_SAVEAS                      275
#define IDS_STATUS_LOADED               276
#define IDS_STATUS_SAVED                277
#define IDS_STATUS_NOTFOUND             278
#define IDS_STATUS_READERROR            279
#define IDS_STATUS_WRITEERROR           280
#define IDS_PROMPT_SAVESTATE            281
#define IDS_PROMPT_SAVEBATTERY          282
#define IDS_STATUS_ROMNOTFOUND          283
#define IDS_STATUS_ROMSIZEDIFFER        284
#define IDS_STATUS_SELECTSTATESLOT      285
#define IDS_STATUS_SELECTFRAMESKIP      286
#define IDS_EMU_INVALIDOPCODE           287
#define IDS_EMU_READACCESSDENIED        288
#define IDS_EMU_WRITEACCESSDENIED       289
#define IDS_EMU_EXECUTEACCESSDENIED     290
#define IDS_EMU_WRITEACCESSDENIED_INT   291
#define IDS_EMU_HALTQUIRK               292
#define IDS_NOAUDIO                     293
#define IDS_OPENAUDIOERROR              294
#define IDS_HIGHERVERSIONREQUIRED       295
#define IDS_TOOLS_CHEAT_MENU            296
#define IDS_TOOLS_CHEAT                 297
#define IDS_CHEAT_TITLE                 298
#define IDS_CHEAT_ADDCHEAT              299
#define IDS_CHEAT_ADDCODE               300
#define IDS_CHEAT_INVALID               301
#define IDS_CHEAT_GAMEGENIE             302
#define IDS_CHEAT_GAMESHARK             303
#define IDS_CHEAT_INEFFECTIVE           304
#define IDS_FILE_SAVESNAPSHOTAS_MENU    305
#define IDS_FILE_SAVESNAPSHOTAS         306
#define IDS_FILE_SAVEVIDEOAS_MENU       307
#define IDS_FILE_SAVEVIDEOAS            308
#define IDS_WND_TILEMAP_XFLIP           309
#define IDS_WND_TILEMAP_YFLIP           310
#define IDS_WND_TILEMAP_PRIORITY        311
#define IDS_WND_TILEMAP_BACKGROUNDENABLED 312
#define IDS_WND_TILEMAP_WINDOWENABLED   313
#define IDS_WND_PALETTES_BACKGROUND     314
#define IDS_WND_PALETTES_SPRITE         315
#define IDS_WND_HARDWARE_ROMSIZE        316
#define IDS_WND_HARDWARE_RAMSIZE        317
#define IDS_WND_REGISTERS_HBLANK        318
#define IDS_WND_REGISTERS_VBLANK        319
#define IDS_WND_REGISTERS_OAMSEARCH     320
#define IDS_WND_REGISTERS_LCDTRANSFER   321
#define IDS_FILE_MERGECHEATS_MENU       322
#define IDS_FILE_MERGECHEATS            323
#define IDS_OPTIONS_FILE                324
#define IDS_OPEN_LOADSTATE              325
#define IDS_OPEN_CHEATXML               326
#define IDS_ENTERADDRESS                327
#define IDS_ENTERROMBANKNO              328
#define IDS_OPTIONS_LANGUAGE_TRANSLATEDBY 329
#define IDS_OPEN_AVI                    330
#define IDS_OPEN_BITMAP                 331
#define IDS_TOOLS_LINKCABLE_MENU        332
#define IDS_TOOLS_LINKCABLE             333
#define IDS_OPTIONS_KEYS_PLAYER         334
#define IDS_OPTIONS_KEYS_SAVESCHEMEAS   335
#define IDS_OPTIONS_KEYS_DELETESCHEME   336
#define IDS_OPTIONS_KEYS_JOYSTICK_NONE  337
#define IDS_OPTIONS_KEYS_JOYSTICK_ANALOG 338
#define IDS_OPTIONS_KEYS_NORMAL         339
#define IDS_OPTIONS_KEYS_AUTOFIRE       340
#define IDS_OPTIONS_KEYS_KEYBOARD       341
#define IDS_OPTIONS_KEYS_JOYSTICK       342
#define IDS_OPTIONS_KEYS_NOKEY          343
#define IDS_OPTIONS_KEYS_SAVESCHEMEAS_TITLE 344
#define IDS_OPTIONS_KEYS_SAVESCHEME_NONAME 345
#define IDS_OPTIONS_KEYS_SAVESCHEMEAS_CANNOTREPLACE 346
#define IDS_FILE_STATESLOT_EMPTY        347
#define IDS_OPTIONS_KEYS_DIRECTION      348
#define IDS_OPTIONS_KEYS_DIRECTION_XY   349
#define IDS_OPTIONS_KEYS_DIRECTION_ENABLED 350
#define IDS_TOOLS_SEARCHCHEAT_MENU      351
#define IDS_TOOLS_SEARCHCHEAT           352
#define IDS_SEARCHCHEAT_TITLE           353
#define IDS_SEARCHCHEAT_BYTE            354
#define IDS_SEARCHCHEAT_WORD            355
#define IDS_SEARCHCHEAT_DWORD           356
#define IDS_SEARCHCHEAT_NEWSEARCH       357
#define IDS_SEARCHCHEAT_HEXADECIMAL     358
#define IDS_SEARCHCHEAT_DECIMAL         359
#define IDS_SEARCHCHEAT_RELATIVEVALUE   360
#define IDS_SEARCHCHEAT_RELATIVELAST    361
#define IDS_SEARCHCHEAT_EQUAL           362
#define IDS_SEARCHCHEAT_NOTEQUAL        363
#define IDS_SEARCHCHEAT_LESSEQUAL       364
#define IDS_SEARCHCHEAT_MOREEQUAL       365
#define IDS_SEARCHCHEAT_LESS            366
#define IDS_SEARCHCHEAT_MORE            367
#define IDS_SEARCHCHEAT_CHEATNAME       368
#define IDS_SEARCHCHEAT_ADDCHEAT        369
#define IDS_SEARCHCHEAT_ADDRESS         370
#define IDS_SEARCHCHEAT_LASTVALUE       371
#define IDS_SEARCHCHEAT_CURRENTVALUE    372
#define IDS_SEARCHCHEAT_ENTERNUMBER     373
#define IDS_SEARCHCHEAT_NOSELECTION     374
#define IDC_AUTOLOADBATTERY             1021
#define IDC_PLAYER                      1022
#define IDC_NUMBER                      1023
#define IDC_SCHEME                      1023
#define IDC_SAVEBATTERY                 1024
#define IDC_KEYBOARD                    1024
#define IDC_FRAMESKIP                   1025
#define IDC_BUTTONTYPE                  1025
#define IDC_FRAMESKIPSPIN               1026
#define IDC_INPUTDEVICES                1026
#define IDC_REGISTERGBROM               1027
#define IDC_DIRECTION                   1027
#define IDC_REGISTERSAVESTATE           1028
#define IDC_DEVICE_BUTTONS              1028
#define IDC_AUTOLOADSTATE               1029
#define IDC_WRITTENBY                   1029
#define IDC_SAVESTATE                   1030
#define IDC_AUTOSTART                   1031
#define IDC_GBTYPE                      1032
#define IDC_LANGUAGELIST                1032
#define IDC_GAMELADHOMEPAGE             1033
#define IDC_FILEASSOC_FRAME             1043
#define IDC_SAVE_FRAME                  1044
#define IDC_SAVEBATTERY_STATIC          1045
#define IDC_SAVESTATE_STATIC            1046
#define IDC_MISC_FRAME                  1047
#define IDC_FRAMESKIP_STATIC            1048
#define IDC_GBTYPE_STATIC               1049
#define IDC_AUTOSTART_STATIC            1050
#define IDC_MESSAGE                     1056
#define IDC_TREE                        1059
#define IDC_CHEAT                       1061
#define IDC_CODE                        1062
#define IDC_TRANSLATOR                  1062
#define IDC_LANGUAGE                    1063
#define IDC_BUTTONLIST                  1066
#define IDC_SAVESCHEMEAS                1067
#define IDC_DELETESCHEME                1068
#define IDC_ENABLEPLAYER                1070
#define IDC_DEVICE_ANALOG               1074
#define IDC_JOYSTICK_ANALOG             1074
#define IDC_KEYBOARD_STATIC             1075
#define IDC_JOYSTICK_STATIC2            1076
#define IDC_JOYSTICK_STATIC             1076
#define IDC_DIRECTION_STATIC            1077
#define IDC_DIRECTION_ENABLED           1078
#define ID_HELP_ABOUT                   40022
#define ID_WINDOW_NEXT                  40033
#define ID_WINDOW_PREVIOUS              40034
#define ID_EMULATION_EXECUTE            40035
#define ID_EMULATION_STOP               40036
#define ID_VIEW_REGISTERS               40037
#define ID_VIEW_DISASSEMBLY             40038
#define ID_TOOLS_OPTIONS                40039
#define ID_EMULATION_STARTDEBUG         40042
#define ID_EMULATION_STEPINTO           40043
#define ID_EMULATION_STEPOVER           40044
#define ID_EMULATION_STEPOUT            40045
#define ID_EMULATION_RUNTOCURSOR        40046
#define ID_FILE_LOADBATTERY             40047
#define ID_FILE_SAVEBATTERY             40048
#define ID_FILE_SAVEBATTERYAS           40049
#define ID_FILE_EXIT                    40050
#define ID_WINDOW_TILEHORIZONTALLY      40052
#define ID_WINDOW_TILEVERTICALLY        40053
#define ID_EMULATION_RESET              40054
#define ID_FILE_CLEARBATTERY            40055
#define ID_VIEW_MEMORY                  40056
#define ID_VIEW_TILES                   40057
#define ID_VIEW_TILEMAP                 40058
#define ID_VIEW_PALETTES                40059
#define ID_VIEW_HARDWARE                40061
#define ID_VIEW_ZOOM_100                40062
#define ID_VIEW_ZOOM_200                40063
#define ID_VIEW_ZOOM_300                40064
#define ID_VIEW_ZOOM_400                40065
#define ID_EMULATION_TOGGLEBREAKPOINT   40067
#define ID_EMULATION_SETNEXTSTATEMENT   40069
#define ID_MEMORY_VBK_BANK0             40070
#define ID_MEMORY_VBK_BANK1             40071
#define ID_MEMORY_ROM                   40072
#define ID_MEMORY_SVBK_BANK1            40075
#define ID_MEMORY_SVBK_BANK2            40076
#define ID_MEMORY_SVBK_BANK3            40077
#define ID_MEMORY_SVBK_BANK4            40078
#define ID_MEMORY_SVBK_BANK5            40079
#define ID_MEMORY_SVBK_BANK6            40080
#define ID_MEMORY_SVBK_BANK7            40081
#define ID_EDIT_GOTO                    40087
#define ID_FILE_SAVESTATE               40093
#define ID_FILE_LOADSTATE               40094
#define ID_FILE_STATESLOT_1             40095
#define ID_FILE_STATESLOT_2             40096
#define ID_FILE_STATESLOT_3             40097
#define ID_FILE_STATESLOT_4             40098
#define ID_FILE_STATESLOT_5             40099
#define ID_FILE_STATESLOT_6             40100
#define ID_FILE_STATESLOT_7             40101
#define ID_FILE_STATESLOT_8             40102
#define ID_FILE_STATESLOT_9             40103
#define ID_FILE_STATESLOT_0             40104
#define ID_VIEW_FRAMESKIP_0             40105
#define ID_VIEW_FRAMESKIP_1             40106
#define ID_VIEW_FRAMESKIP_2             40107
#define ID_VIEW_FRAMESKIP_3             40108
#define ID_VIEW_FRAMESKIP_4             40109
#define ID_VIEW_FRAMESKIP_5             40110
#define ID_VIEW_FRAMESKIP_6             40111
#define ID_VIEW_FRAMESKIP_7             40112
#define ID_VIEW_FRAMESKIP_8             40113
#define ID_VIEW_FRAMESKIP_9             40114
#define ID_FILE_SAVESTATEAS             40115
#define ID_FILE_LOADSTATEAS             40117
#define ID_SAVESTATESLOT                40118
#define ID_TOOLS_SOUNDENABLED           40119
#define ID_VIEW_STATUSBAR               40120

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         40121
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           163
#endif
#endif
