//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Game Lad.rc
//
#define IDS_FILE_OPEN                   1
#define IDS_FILE_CLOSE                  2
#define IDS_FILE_SAVESTATE              3
#define IDS_FILE_LOADSTATE              4
#define IDS_FILE_SAVESTATEAS            5
#define IDS_FILE_LOADSTATEAS            6
#define IDS_FILE_STATESLOT_0            7
#define IDS_FILE_STATESLOT_1            8
#define IDS_FILE_STATESLOT_2            9
#define IDS_FILE_STATESLOT_3            10
#define IDS_FILE_STATESLOT_4            11
#define IDS_FILE_STATESLOT_5            12
#define IDS_FILE_STATESLOT_6            13
#define IDS_FILE_STATESLOT_7            14
#define IDS_FILE_STATESLOT_8            15
#define IDS_FILE_STATESLOT_9            16
#define IDS_FILE_SAVEBATTERY            17
#define IDS_FILE_LOADBATTERY            18
#define IDS_FILE_SAVEBATTERYAS          19
#define IDS_FILE_CLEARBATTERY           20
#define IDS_FILE_EXIT                   21
#define IDS_EDIT_GOTO                   22
#define IDS_VIEW_DISASSEMBLY            23
#define IDS_VIEW_MEMORY                 24
#define IDS_VIEW_REGISTERS              25
#define IDS_VIEW_HARDWARE               26
#define IDS_VIEW_PALETTES               27
#define IDS_VIEW_TILEMAP                28
#define IDS_VIEW_TILES                  29
#define IDS_VIEW_STATUSBAR              30
#define IDS_VIEW_ZOOM_100               31
#define IDS_VIEW_ZOOM_200               32
#define IDS_VIEW_ZOOM_300               33
#define IDS_VIEW_ZOOM_400               34
#define IDS_VIEW_FRAMESKIP_0            35
#define IDS_VIEW_FRAMESKIP_1            36
#define IDS_VIEW_FRAMESKIP_2            37
#define IDS_VIEW_FRAMESKIP_3            38
#define IDS_VIEW_FRAMESKIP_4            39
#define IDS_VIEW_FRAMESKIP_5            40
#define IDS_VIEW_FRAMESKIP_6            41
#define IDS_VIEW_FRAMESKIP_7            42
#define IDS_VIEW_FRAMESKIP_8            43
#define IDS_VIEW_FRAMESKIP_9            44
#define IDS_MEMORY_ROM                  45
#define IDS_MEMORY_VBK_BANK0            46
#define IDS_MEMORY_VBK_BANK1            47
#define IDS_MEMORY_RAM_BANK0            48
#define IDS_MEMORY_RAM_BANK1            49
#define IDS_MEMORY_RAM_BANK2            50
#define IDS_MEMORY_RAM_BANK3            51
#define IDS_MEMORY_RAM_BANK4            52
#define IDS_MEMORY_RAM_BANK5            53
#define IDS_MEMORY_RAM_BANK6            54
#define IDS_MEMORY_RAM_BANK7            55
#define IDS_MEMORY_RAM_BANK8            56
#define IDS_MEMORY_RAM_BANK9            57
#define IDS_MEMORY_RAM_BANK10           58
#define IDS_MEMORY_RAM_BANK11           59
#define IDS_MEMORY_RAM_BANK12           60
#define IDS_MEMORY_RAM_BANK13           61
#define IDS_MEMORY_RAM_BANK14           62
#define IDS_MEMORY_RAM_BANK15           63
#define IDS_MEMORY_SVBK_BANK1           64
#define IDS_MEMORY_SVBK_BANK2           65
#define IDS_MEMORY_SVBK_BANK3           66
#define IDS_MEMORY_SVBK_BANK4           67
#define IDS_MEMORY_SVBK_BANK5           68
#define IDS_MEMORY_SVBK_BANK6           69
#define IDS_MEMORY_SVBK_BANK7           70
#define IDS_EMULATION_STARTDEBUG        71
#define IDS_EMULATION_EXECUTE           72
#define IDS_EMULATION_STOP              73
#define IDS_EMULATION_STEPINTO          74
#define IDS_EMULATION_STEPOVER          75
#define IDS_EMULATION_STEPOUT           76
#define IDS_EMULATION_RUNTOCURSOR       77
#define IDS_EMULATION_SETNEXTSTATEMENT  78
#define IDS_EMULATION_TOGGLEBREAKPOINT  79
#define IDS_EMULATION_RESET             80
#define IDS_TOOLS_OPTIONS               81
#define IDS_TOOLS_SOUNDENABLED          82
#define IDS_WINDOW_NEXT                 83
#define IDS_WINDOW_PREVIOUS             84
#define IDS_WINDOW_CASCADE              85
#define IDS_WINDOW_TILEHORIZONTALLY     86
#define IDS_WINDOW_TILEVERTICALLY       87
#define IDS_HELP_ABOUT                  88
#define IDR_MENU                        101
#define IDI_MAINICON                    106
#define IDD_ABOUT                       107
#define IDD_OPTIONS_KEYS                108
#define ID_MEMORY_RAM_BANK0             115
#define IDR_ACCELERATOR                 116
#define ID_MEMORY_RAM_BANK1             116
#define ID_MEMORY_RAM_BANK2             117
#define IDB_CURRENTSTATEMENT            118
#define ID_MEMORY_RAM_BANK3             118
#define IDB_BREAKPOINT                  119
#define ID_MEMORY_RAM_BANK4             119
#define IDI_ICON1                       120
#define ID_MEMORY_RAM_BANK5             120
#define IDI_ICON2                       121
#define ID_MEMORY_RAM_BANK6             121
#define IDI_ICON3                       122
#define ID_MEMORY_RAM_BANK7             122
#define IDI_ICON4                       123
#define ID_MEMORY_RAM_BANK8             123
#define IDI_ICON5                       124
#define ID_MEMORY_RAM_BANK9             124
#define IDI_ICON6                       125
#define ID_MEMORY_RAM_BANK10            125
#define IDR_POPUPMENU                   126
#define ID_MEMORY_RAM_BANK11            126
#define ID_MEMORY_RAM_BANK12            127
#define IDD_ENTERNUMBER                 127
#define ID_MEMORY_RAM_BANK13            128
#define IDD_OPTIONS_GENERAL             128
#define ID_MEMORY_RAM_BANK14            129
#define ID_MEMORY_RAM_BANK15            130
#define ID_TILEMAP_PALETTENO            131
#define ID_TILEMAP_FLIPX                132
#define ID_TILEMAP_FLIPY                133
#define ID_TILEMAP_PRIORITY             134
#define ID_TILEMAP_TILENO               136
#define ID_TILEMAP_TILEDATA             137
#define ID_TILEMAP_BGADDRESS            138
#define ID_TILEMAP_WNDADDRESS           139
#define ID_TILEMAP_BGENABLED            140
#define ID_TILEMAP_WNDENABLED           141
#define ID_TILES_PALETTENO              142
#define IDC_UP                          1020
#define IDC_AUTOLOADBATTERY             1021
#define IDC_NUMBER                      1023
#define IDC_DOWN                        1024
#define IDC_SAVEBATTERY                 1024
#define IDC_LEFT                        1025
#define IDC_FRAMESKIP                   1025
#define IDC_RIGHT                       1026
#define IDC_FRAMESKIPSPIN               1026
#define IDC_A                           1027
#define IDC_REGISTERGBROM               1027
#define IDC_B                           1028
#define IDC_REGISTERSAVESTATES          1028
#define IDC_REGISTERSAVESTATE           1028
#define IDC_START                       1029
#define IDC_AUTOLOADSTATE               1029
#define IDC_SELECT                      1030
#define IDC_SAVESTATE                   1030
#define IDC_FASTFORWARD                 1031
#define IDC_AUTOSTART                   1031
#define IDC_GBTYPE                      1032
#define ID_HELP_ABOUT                   40022
#define ID_WINDOW_NEXT                  40033
#define ID_WINDOW_PREVIOUS              40034
#define ID_EMULATION_EXECUTE            40035
#define ID_EMULATION_STOP               40036
#define ID_VIEW_REGISTERS               40037
#define ID_VIEW_DISASSEMBLY             40038
#define ID_TOOLS_OPTIONS                40039
#define ID_EMULATION_STARTDEBUG         40042
#define ID_EMULATION_STEPINTO           40043
#define ID_EMULATION_STEPOVER           40044
#define ID_EMULATION_STEPOUT            40045
#define ID_EMULATION_RUNTOCURSOR        40046
#define ID_FILE_LOADBATTERY             40047
#define ID_FILE_SAVEBATTERY             40048
#define ID_FILE_SAVEBATTERYAS           40049
#define ID_FILE_EXIT                    40050
#define ID_WINDOW_TILEHORIZONTALLY      40052
#define ID_WINDOW_TILEVERTICALLY        40053
#define ID_EMULATION_RESET              40054
#define ID_FILE_CLEARBATTERY            40055
#define ID_VIEW_MEMORY                  40056
#define ID_VIEW_TILES                   40057
#define ID_VIEW_TILEMAP                 40058
#define ID_VIEW_PALETTES                40059
#define ID_VIEW_HARDWARE                40061
#define ID_VIEW_ZOOM_100                40062
#define ID_VIEW_ZOOM_200                40063
#define ID_VIEW_ZOOM_300                40064
#define ID_VIEW_ZOOM_400                40065
#define ID_EMULATION_TOGGLEBREAKPOINT   40067
#define ID_EMULATION_SETNEXTSTATEMENT   40069
#define ID_MEMORY_VBK_BANK0             40070
#define ID_MEMORY_VBK_BANK1             40071
#define ID_MEMORY_ROM                   40072
#define ID_MEMORY_SVBK_BANK1            40075
#define ID_MEMORY_SVBK_BANK2            40076
#define ID_MEMORY_SVBK_BANK3            40077
#define ID_MEMORY_SVBK_BANK4            40078
#define ID_MEMORY_SVBK_BANK5            40079
#define ID_MEMORY_SVBK_BANK6            40080
#define ID_MEMORY_SVBK_BANK7            40081
#define ID_EDIT_GOTO                    40087
#define ID_FILE_SAVESTATE               40093
#define ID_FILE_LOADSTATE               40094
#define ID_FILE_STATESLOT_1             40095
#define ID_FILE_STATESLOT_2             40096
#define ID_FILE_STATESLOT_3             40097
#define ID_FILE_STATESLOT_4             40098
#define ID_FILE_STATESLOT_5             40099
#define ID_FILE_STATESLOT_6             40100
#define ID_FILE_STATESLOT_7             40101
#define ID_FILE_STATESLOT_8             40102
#define ID_FILE_STATESLOT_9             40103
#define ID_FILE_STATESLOT_0             40104
#define ID_VIEW_FRAMESKIP_0             40105
#define ID_VIEW_FRAMESKIP_1             40106
#define ID_VIEW_FRAMESKIP_2             40107
#define ID_VIEW_FRAMESKIP_3             40108
#define ID_VIEW_FRAMESKIP_4             40109
#define ID_VIEW_FRAMESKIP_5             40110
#define ID_VIEW_FRAMESKIP_6             40111
#define ID_VIEW_FRAMESKIP_7             40112
#define ID_VIEW_FRAMESKIP_8             40113
#define ID_VIEW_FRAMESKIP_9             40114
#define ID_FILE_SAVESTATEAS             40115
#define ID_FILE_LOADSTATEAS             40117
#define ID_SAVESTATESLOT                40118
#define ID_TOOLS_SOUNDENABLED           40119
#define ID_VIEW_STATUSBAR               40120

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         40121
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           143
#endif
#endif
